### ISSUE TITLE
D1.Nodejs 入门篇

### ISSUE THREAD

**Issue by vincenting** [vincenting/note#1]
分享第一篇，关于 NodeJS —— Javascript 的常用知识以及如何从 Javascript 开发者过渡到 NodeJS 开发者（不会介绍具体的框架）。在读本文前，希望你对 javascript 有一些初步的认识。

Javascript 是一门原型模型的解释型语言。解释型将在后面的 NodeJS 里面讨论，原型链是 ES6 之前的 Javascript 的面向对象的实现方式之一，在 ES6 中支持的 class 增加了一种新的实现方式。在 Javascript 里面所有东西都是对象，包括 “类”。接触过 ruby/python 的元编程的可能会觉得这个很熟悉，Javascript 也很容易是实现出动态的生成类的方法。
### 1. 基于原型链实现的简单的“类”

``` javascript
var Person = function(name){
  this.name = name;
};

Person.staticSay = function(name){
  console.log('Hello ' + name);
};

Person.prototype.sayHi = function(){
  Person.staticSay(this.name);
}
```

提一些常见的规范，例如 Javascript 中所有的方法都是驼峰命名，优先使用单引号，两个空格等等，更多的规范可以参考 https://github.com/airbnb/javascript 。

代码中的`staticSay`为静态方法，即只能通过 `Person.staticSay`来调用。 当上面的 `Person` 生成实例的时候，例如 `var vincent = new Person('vincent');`的时候，`vincent`会自动继承 `Person.prototype` 的所有方法（代码中的 `this` 指代的是当前上下文，即上文中的 `vincent`）。

同时也可以动态的为对象 `vincent` 添加方法，例如如下代码：

``` javascript
var vincent = new Person('vincent')
vincent.tellName = function(){
  console.log('Hi, i\'m am' + this.name)
};
```

然后当你需要模拟继承的时候，就需要在 `prototype` 上下功夫。例如下面使用 `Worker.prototype = new Person()` 来实现，`new Person()` 返回的实例对象带着的所有方法、属性都被赋给了 `prototype`，变相模拟了继承。这种方式最终一层层的往上找 `prototype` 里面的内容（因为每个实例具有的方法都在 `prototype` 里面，往上直到 `Object`）。当然也可以通过遍历来进行对 `prototype` 赋值来模拟继承。
### 2. 上下文切换

上下文最直观的表现就是代码块中的 `this`，通常在面向对象的编程中用到，来指代当前“类”生成的对应实例，与其他语言的 `self`一致。

继续用上文中的例子，上文中已经实现了一个 `Person.prototype.sayHi`方法，现在我有一个新的对象，代码如下：

``` javascript
var Cat = function(name){
  this.name = name;
}

var c = new Cat('tomcat');
```

如果某天突然异想天开希望这只猫像人一样介绍他自己怎么办，他自己没有 `sayHi` 这个方法。但是可以通过 `console.log(Person.prototype.sayHi)`是可以拿到人类的 `sayHi` 方法的，怎么让猫也可以使用呢？

Javascript 有两个方法，`call` 和 `apply`，他们的区别就是参数不同（自行谷歌），作用是用来切换上下文。简单说就是可以把 `Person.prototype.sayHi`这个函数中的 `this` 变成其他对象。使用方式： `Person.prototype.sayHi.call(c)`。

这个实用嘛？例如如下场景：

``` javascript
var doSomething = function(){
  var persons = arguments;
};
```

上面的函数中，通过关键字 `arguments`获取所有的参数来支持不定数量的参数。现在我们希望对 `persons`用一些原属于 Array 类型的方法，如何实现呢？这里就可以用上下文切换来实现：

``` javascript
var doSomething = function(){
  var persons = arguments;
  // 使用 Array 的 slice 方法，将 arguments 对象转变为 Array 实例
  var persons_arr = Array.prototype.slice.call(arguments);
};
```
### 3. 闭包

先来段常见的代码

``` javascript
for (var i = 0; i < 3; i ++){
  setTimeout(function(){
    console.log(i);
  }, i)
}
```

这个会输出什么结果呢？依次输出 0 1 2 ？实际情况是，当 `setTimeout`第一次执行回调的时候，for 循环已经结束了，也就是说此时的 `i` 已经是 3 了，导致最终的输出结果是 3 3 3。

当你需要保护某一个变量，使得他不被外围的代码所影响的时候，你可能就需要考虑下闭包 —— 一个封闭的作用域的代码块。

``` javascript
for (var i = 0; i < 3; i ++){
  +function(i){
    setTimeout(function(){
      console.log(i);
    }, i)
  }(i)
}
```

咦， `+`是干嘛的，有没有其他方式实现，请自行谷歌。闭包内的 i 的作用域是一个封闭的作用域，所以最终 闭包内的 i 一直没有被外面的执行改变，所以可以成功的输出 0 1 2。 

---

简单的介绍了 javascript 部分特性，关键字 原型链、call 和 apply、arguments 关键字，更多的建议可以看看例如权威指南这样的书，或者快速了解下基本的类型以及每个类型有的方法。有一些比较神奇的代码，例如获得当前的代码的字符串，然后进行处理得到自己想要的内容，使用 getter 和 setter 在用户对对象属性获取或者赋值的时候做一些特殊的操作等等。
### 4. NodeJS 和 Javascript 的开发区别

这块主要介绍 `require` 加载的基础知识，首先先介绍一些代码:

``` javascript
// a.js
module.exports = {
  name: "a",
  doSomething: function(){
    return "something";
  }
}

// b.js
var a = require('./a')
global.a_name = a.name;

// c.js
require('./b');
console.log(a_name) // 执行后打印 a 
```

当我们执行 `node c.js`的时候发生了什么？
1. `require`是 nodes  关键字，虽然 NodeJS 是以异步著称，但是他的 `require`都是阻塞的。否则就会出现还没有载入其他模块，已经开始执行下面的代码的情况。
2. `require.resolve()`方法是用来找出你所引用的文件的实际路径，找出后 Nodejs 会在 `require.cache`里面寻找是否有缓存，没有的话则会读取文件然后解析，所以通常情况下，一个 js 文件里面的执行的代码只会在第一次被 require 的时候被执行。（tip. require.cache 如果有需要的话是可以手动删除一些东西的，然后可以某种程度上可以执行多次）
3. 当 b.js 开始执行的时候，他需要先载入 a.js，`module.exports`告诉 Nodejs 这个文件对外暴露写什么，例如 a.js 暴露的是一个对象，包含 name 属性和 doSomething 方法。然后 b.js 中的 a 变量其实就是这个对象。
4. 执行完获取 a.js 后，继续回到 b.js ，`global.a_name` 相当于声明了一个全局变量，这个和前端中的 `window.a_name = a.name` 效果类似。
5. 最终过程完成，c.js 执行输出值。
### 5. 异步的底层原理

NodeJS 很容易给人一种使用上的错觉，就是写了很久都可能不知道底层的异步是怎么实现的。（下面的理解主要来自于对 python3.4 中的 asyncio 的理解，如有错误欢迎指出）。

NodeJS 底层的 libev 分别在 Window 下使用 IOCP 和 *nix 下使用基于 AIO 的 libeio 来实现异步。通过系统层面的技术，最后达到一个目的，就是应用程序发起一个异步请求，最终在系统执行完后，系统通知应用程序处理完成。在这个过程中，应用程序可以将之前的处理挂起/推入线程池中等待执行，而应用程序在此期间可以执行其他任务。

整个的运行通过系统层面的事件循环来进行运作。例如  Python 提供了类似于 run_until 以及 run_forever 的这样的方法，保证在异步执行之前程序不会结束运行。将整个异步想象成一个一直在运作的车间，车间里面的机器负责查看包裹并盖章这样的操作，工人拿到了一个包裹，然后贴上相应的标签后放进去，等车间处理完后再交还给工人，工人根据包裹上他之前贴上的标签和被车间贴上的标签，进行下一步的处理。工人无需等待包裹检查完毕才能进行下一个，他只需要接受简单处理，然后放入车间进行检查。然后等某个时间车间返回给他某个包裹，他再去进行下一步的操作。

---

目前主要还是只介绍了一些语言层面的知识，但是只有这些距离开发一个完整的 web 还有一些距离，将在后面继续介绍。包括 Redis，Nginx，测试驱动等等。

**Comment by geminiyellow** [comment]
+1

**Comment by markyun** [comment]
喝酒喝酒、
